version: '3.7'
services:
  nginx:
    container_name: kekeek-nginx
    image: nginx:1.13
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
