[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="mainContent" type="java.lang.String" --]
[#-- @ftlvariable name="latestArticles" type="java.lang.String" file="templates/index.ftl" --]
[#-- @ftlvariable name="faq" type="java.lang.String" file="templates/index.ftl" --]
[#-- @ftlvariable name="centerLinks" type="java.lang.String" file="templates/index.ftl" --]
[#-- @ftlroot "templates" --]
